language: generic

sudo: required

services:
  - docker

matrix:
  include:
    - os: linux
      env: TARGET=Linux   VLC_VERSION=2.1 DEBIAN=wheezy-backports
    - os: linux
      env: TARGET=Linux   VLC_VERSION=2.2 DEBIAN=stretch
    - os: linux
      env: TARGET=Linux   VLC_VERSION=3.0 DEBIAN=experimental
    - os: linux
      env: TARGET=Windows VLC_VERSION=2.1
    - os: linux
      env: TARGET=Windows VLC_VERSION=2.2
    - os: linux
      env: TARGET=Windows VLC_VERSION=3.0
    - os: osx
      env: TARGET=macOS   VLC_VERSION=2.1
      language: c
      osx_image: xcode7.3
    - os: osx
      env: TARGET=macOS   VLC_VERSION=2.2
      language: c
      osx_image: xcode7.3
    - os: osx
      env: TARGET=macOS   VLC_VERSION=3.0
      language: c
      osx_image: xcode7.3

script:
  - ./.travis/script.sh
